###############################################################################
# Micron System V3 - i386 Processor Driver Build Sub-system
# Copyright (C) 2007, Huaxin Tang
# martintang25 AT gmail.com
###############################################################################

# Compiler Flags
CCFLAGS+=-I include/arch-i386
CXXFLAGS+=-I include/arch-i386

# Linker Script Selection
BLLDSCRIPT=arch/i386/bootloader/bootloader.ld
LDSCRIPT=arch/i386/kernel.ld

# Bootloader Targets
BOOTOBJS+=arch/i386/bootloader/bootloader.o

# Targets
OBJECTS+=arch/i386/init.o

